# Generated by Django 5.2.4 on 2025-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(default='', upload_to='thumbnails/'),
        ),
    ]
