# Generated by Django 5.2.4 on 2025-08-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_thumbnail_url_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        # Rename the old field to store the data temporarily
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='category_old',
        ),
        # Add the new ForeignKey field, allowing it to be null temporarily
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.category'),
        ),
    ]
