# Generated by Django 5.0.7 on 2025-08-25 15:09

from django.db import migrations

def migrate_categories(apps, schema_editor):
    Video = apps.get_model('videos', 'Video')
    Category = apps.get_model('videos', 'Category')
    for video in Video.objects.all():
        if video.category_old:
            category_name = video.category_old # This is a string
            category_obj, created = Category.objects.get_or_create(name=category_name)
            video.category = category_obj
            video.save()


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_category_alter_video_category'),
    ]

    operations = [
        migrations.RunPython(migrate_categories),
    ]
