# Generated by Django 5.0.7 on 2025-08-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20250825_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category_old',
        ),
    ]
